imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

doctrine_mongodb:
    connections:
        default:
            server: mongodb://127.0.0.1:27017
            options: {}
    default_database: %database_name%_%kernel.environment%
    document_managers:
        default:
            auto_mapping: true
            #filters:
            #    softdeleteable:
            #        class: Gedmo\SoftDeleteable\Filter\ODM\SoftDeleteableFilter
            #        enabled: true

stof_doctrine_extensions:
    mongodb:
        default:
            softdeleteable: true

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
        api: auto
        strict_email: true
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    trusted_hosts:   ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'Lighthouse\CoreBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - "NelmioApiDocBundle"
        - "ClamidityProfilerBundle"
    filters:
        cssrewrite: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    encryption: ssl
    spool:     { type: memory }

jms_di_extra:
    locations:
        all_bundles: false
        bundles:
            - LighthouseCoreBundle
            - LighthouseIntegrationBundle
            - LighthouseReportsBundle
            - LighthouseJobBundle
        directories: ["%kernel.root_dir%/../src"]

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - {path: '^/api/', priorities: ['json']}
            - {path: '^/oauth/', priorities: ['json']}
            - {path: '^/', priorities: ['html', '*/*']}
    routing_loader:
        default_format: json
    view:
        view_response_listener: force
        formats:
            html: false
            xml: true
            json: true
        templating_formats:
            html: false
    exception:
        codes:
            'Lighthouse\CoreBundle\Exception\NotEmptyException': 409
        messages:
            'Lighthouse\CoreBundle\Exception\NotEmptyException': true

nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization', 'Link', 'X-File-Name']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'LINK', 'UNLINK']
            max_age: 3600
        '^/oauth/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'LINK', 'UNLINK']
            max_age: 3600

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

fos_oauth_server:
    db_driver: mongodb
    client_class:        Lighthouse\CoreBundle\Document\Auth\Client
    access_token_class:  Lighthouse\CoreBundle\Document\Auth\AccessToken
    refresh_token_class: Lighthouse\CoreBundle\Document\Auth\RefreshToken
    auth_code_class:     Lighthouse\CoreBundle\Document\Auth\AuthCode
    service:
        user_provider: lighthouse.core.user.provider
        options:
            access_token_lifetime: 86400

nelmio_api_doc:
    name: Lighthouse API

ekino_new_relic:
    application_name: "Dreamkas API %kernel.environment%"
    api_key: 123e886f0c6641b422f9f035980c8f2966177d25

leezy_pheanstalk:
    enabled: true
    pheanstalks:
        primary:
            server: %beanstalkd_server%
            default: true
            proxy: lighthouse.job.pheanstalk

clamidity_profiler:
    enabled: false
    location_reports: "%kernel.root_dir%/logs"

ornicar_apc:
    host: "%web_host%"
    web_dir: "%kernel.root_dir%/../web"
    mode: curl

lighthouse_core:
    selectel:
        auth:
            username: 36480
            password: 1avrj2rw
        container: "%database_name%_%kernel.environment%"

lighthouse_job:
    tube_prefix: "%database_name%_%kernel.environment%"