imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

ekino_new_relic:
    application_name: Lighthouse API tests

doctrine_mongodb:
    default_database: "%database_name%_%kernel.environment%%karzer.thread%"
    document_managers:
        default:
            mappings:
                LighthouseCoreBundleTest:
                    type: annotation
                    dir: %kernel.root_dir%/../src/Lighthouse/CoreBundle/Tests/Fixtures/Document
                    prefix: Lighthouse\CoreBundle\Tests\Fixtures\Document
                    is_bundle: false

lighthouse_core:
    job:
        tube_prefix: "%database_name%_%kernel.environment%%karzer.thread%"
    selectel:
        auth:
            url: 'http://unknown.host'
            username: test
            password: password
