parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     lighthouse
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       smtp.yandex.ru
    mailer_user:       noreply@lighthouse.pro
    mailer_password:   A1234567a

    locale:            ru
    secret:            kjhf843f34nbfi34fed23efedf34

    beanstalkd_server: 127.0.0.1

    web_host: http://api.lighthouse.dev
