lighthouse.core:
    type: rest
    resource: "@LighthouseCoreBundle/Resources/config/routing.yml"
    prefix: /api/1

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

debug:
    resource: Lighthouse\CoreBundle\Controller\DebugController
    type:     annotation
    prefix: /

clamidity_profile:
    resource: "@ClamidityProfilerBundle/Resources/config/routing.yml"