lighthouse.core.store:
    resource: Lighthouse\CoreBundle\Controller\StoreController
    type:     rest

lighthouse.core.product:
    resource: Lighthouse\CoreBundle\Controller\ProductController
    type:     rest

lighthouse.core.invoice:
    resource: Lighthouse\CoreBundle\Controller\InvoiceController
    parent:   lighthouse.core.store
    type:     rest

lighthouse.core.invoice.product:
    resource: Lighthouse\CoreBundle\Controller\InvoiceProductController
    parent:   lighthouse.core.invoice
    type:     rest

lighthouse.core.purchase:
    resource: Lighthouse\CoreBundle\Controller\PurchaseController
    type:     rest

lighthouse.core.write-off:
    resource: Lighthouse\CoreBundle\Controller\WriteOffController
    type:     rest

lighthouse.core.write-off.product:
    resource: Lighthouse\CoreBundle\Controller\WriteOffProductController
    parent:   lighthouse.core.write-off
    type:     rest

lighthouse.core.group:
    resource: Lighthouse\CoreBundle\Controller\GroupController
    type:     rest

lighthouse.core.category:
    resource: Lighthouse\CoreBundle\Controller\CategoryController
    type:     rest

lighthouse.core.subcategory:
    resource: Lighthouse\CoreBundle\Controller\SubCategoryController
    type:     rest

lighthouse.core.store.product:
    resource: Lighthouse\CoreBundle\Controller\StoreProductController
    type:     rest

lighthouse.core.department:
    resource: Lighthouse\CoreBundle\Controller\DepartmentController
    type:     rest

lighthouse.core.user:
    resource: Lighthouse\CoreBundle\Controller\UserController
    type:     rest

lighthouse.core.job:
    resource: Lighthouse\CoreBundle\Controller\JobController
    type:     rest

lighthouse.core.rounding:
    resource: Lighthouse\CoreBundle\Controller\RoundingController
    type:     rest

lighthouse.core.config:
    resource: Lighthouse\CoreBundle\Controller\ConfigController
    type:     rest

lighthouse.core.integration:
    resource: Lighthouse\CoreBundle\Controller\IntegrationController
    type:     rest

lighthouse.core.service:
    resource: Lighthouse\CoreBundle\Controller\ServiceController
    type:     annotation
