lighthouse.core.product:
    resource: Lighthouse\CoreBundle\Controller\ProductController
    type:     rest

lighthouse.core.invoice:
    resource: Lighthouse\CoreBundle\Controller\InvoiceController
    type:     rest

lighthouse.core.invoice.product:
    resource: Lighthouse\CoreBundle\Controller\InvoiceProductController
    parent:   lighthouse.core.invoice
    type:     rest

lighthouse.core.purchase:
    resource: Lighthouse\CoreBundle\Controller\PurchaseController
    type:     rest

lighthouse.core.write-off:
    resource: Lighthouse\CoreBundle\Controller\WriteOffController
    type:     rest

lighthouse.core.write-off.product:
    resource: Lighthouse\CoreBundle\Controller\WriteOffProductController
    type:     rest
    parent:   lighthouse.core.write-off

lighthouse.core.klass:
    resource: Lighthouse\CoreBundle\Controller\KlassController
    type:     rest

lighthouse.core.group:
    resource: Lighthouse\CoreBundle\Controller\GroupController
    type:     rest

lighthouse.core.user:
    resource: Lighthouse\CoreBundle\Controller\UserController
    type:     rest

lighthouse.core.service:
    resource: Lighthouse\CoreBundle\Controller\ServiceController
    type:     annotation
