lighthouse.core.product:
    resource: Lighthouse\CoreBundle\Controller\ProductController
    type:     rest

lighthouse.core.invoice:
    resource: Lighthouse\CoreBundle\Controller\InvoiceController
    type:     rest

lighthouse.core.invoice_product:
    resource: Lighthouse\CoreBundle\Controller\InvoiceProductController
    parent:   lighthouse.core.invoice
    type:     rest

lighthouse.core.service:
    resource: Lighthouse\CoreBundle\Controller\ServiceController
    type:     annotation